### ISSUE TITLE
Error when compiling wasm-table.wat

### ISSUE THREAD

**Issue by kablaa** [mdn/webassembly-examples#10] opened 2018-01-16 20:46 UTC
wasm-table.wat:11:20: error: unexpected token $return_i32, expected ).
    (call_indirect $return_i32)

**Comment by caugner** [comment] 2023-10-11 16:59
The issue refers to https://github.com/mdn/webassembly-examples/blob/main/understanding-text-format/wasm-table.wat, which can be seen here: https://mdn.github.io/webassembly-examples/understanding-text-format/wasm-table.html

For me, the console output is as follows.

In Firefox 120 (Nightly):

```
42
13
Uncaught (in promise) RuntimeError: index out of bounds
    <anonymous> https://mdn.github.io/webassembly-examples/understanding-text-format/wasm-table.html:16
    promise callback* https://mdn.github.io/webassembly-examples/understanding-text-format/wasm-table.html:13
```

In Chrome 117:

```
42
13
Uncaught (in promise) RuntimeError: table index is out of bounds
    at wasm-table.wasm:0x50
    at wasm-table.html:16:42
```

In Safari 17:

```
42
13
Unhandled Promise Rejection: RuntimeError: Out of bounds call_indirect (evaluating 'obj.instance.exports.callByIndex(2)')
```

I cannot reproduce the compiling error, so I'm closing this issue as wontfix.

**Closed by caugner** 2023-10-11 16:59 UTC
Labels: needs triage
